// npm run bank:export  Writes content/review/bank-review.md and bank-review.csv for review.
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { checkBank, isLongestStrict } from '@/lib/bank/check';
import { testwiseGuess } from '@/lib/bank/testwise';
import { DOMAINS, DOMAIN_NAMES } from '@/lib/config/tracks';
import { OPTION_IDS } from '@/lib/bank/schema';
import { toCsv } from '@/lib/admin/stats';
import { readBankFiles } from './bank-files';
import reviewNotes from '@/content/review/notes.json';

const notes = reviewNotes as Record<string, string>;
const { items, findings } = checkBank(readBankFiles());
const flagsFor = (id: string) => {
  const q = items.find((x) => x.id === id)!;
  const f = findings.filter((x) => x.id === id).map((x) => `${x.level}: ${x.message}`);
  const tw = testwiseGuess(q);
  if (tw.guess === q.answer) f.push(`test-wise: answerable from cues (${tw.cues.join(', ')})`);
  if (notes[id]) f.push(`reviewer note: ${notes[id]}`);
  return f;
};

const md: string[] = [
  '# Question bank review',
  '',
  `Generated by npm run bank:export. ${items.length} items. Key marked with ✔. Statuses: draft until reviewed.`,
  '',
  'Review protocol (docs/SPEC.md section 17): every tier-1 item, every flagged item, and a random 10% of the rest.',
  '',
];
const csv: (string | number | null)[][] = [['id', 'domain', 'tier', 'status', 'stem', 'a', 'b', 'c', 'd', 'answer', 'explanation', 'source', 'keep_order', 'flags']];
for (const d of DOMAINS) {
  md.push(`## ${d}: ${DOMAIN_NAMES[d]}`, '');
  for (const t of [1, 2, 3]) {
    const cell = items.filter((q) => q.domain === d && q.tier === t);
    if (!cell.length) continue;
    md.push(`### ${d} tier ${t} (${cell.length} items)`, '');
    for (const q of cell) {
      const flags = flagsFor(q.id);
      md.push(`**${q.id}** (${q.status}${q.keepOrder ? ', fixed order' : ''}) ${q.stem}`, '');
      for (const o of OPTION_IDS) md.push(`- ${o === q.answer ? '✔ ' : ''}${o}. ${q.options[o]}`);
      md.push('', `*Why:* ${q.explanation} *Source:* ${q.source}.`);
      if (flags.length) md.push('', `*Flags:* ${flags.join('; ')}`);
      md.push('');
      csv.push([q.id, q.domain, q.tier, q.status, q.stem, q.options.a, q.options.b, q.options.c, q.options.d, q.answer, q.explanation, q.source, q.keepOrder ? 'yes' : 'no', flags.join('; ')]);
    }
  }
}
const dir = path.join(process.cwd(), 'content', 'review');
writeFileSync(path.join(dir, 'bank-review.md'), md.join('\n'));
writeFileSync(path.join(dir, 'bank-review.csv'), toCsv(csv));
const tw = items.filter((q) => testwiseGuess(q).guess === q.answer).length;
console.log(`Wrote content/review/bank-review.md and .csv (${items.length} items, ${tw} answerable from cues, ${items.filter(isLongestStrict).length} with the key strictly longest).`);
